articlee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('users.urls')),
    path('', include('personal.urls')),
    path('', include('public.urls')),
]


handler403 = 'core.views.error_403_handler'
handler404 = 'core.views.error_404_handler'

core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from core import views


app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('become_user/',
         TemplateView.as_view(template_name='core/become_user.html'), name='become-user'),
]

personal/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'personal'
urlpatterns = [
    # View for seeing personal page
    path('personal/', views.PersonalPageView.as_view(), name='personal-page'),
    # Views for publishing, updating, deleting articles
    path('personal/articles/', views.ArticlesListView.as_view(), name='articles-list'),
    path('personal/articles/<int:pk>/',
         views.ArticleDetailView.as_view(), name='article-detail'),
    path('personal/articles/publish/',
         views.PublishArticleView.as_view(), name='publish-article'),
    path('personal/articles/list/<int:pk>/update/',
         views.UpdateArticleThroughArticlesList.as_view(), name='update-article-list'),
    path('personal/articles/<int:pk>/update/',
         views.UpdateArticleThroughArticleDetail.as_view(), name='update-article-detail'),
    path('personal/articles/<int:pk>/delete/',
         views.DeleteArticleView.as_view(), name='delete-article'),
    # Views for manipulations on about page: creating, updating, deleting user's
    # description; creating, deleting social media links, and showing needed information
    # on about page, such as date when user joined the website, how many times
    # user's articles were read, etc..
    path('personal/about/', views.AboutPageView.as_view(), name='about-page'),
    path('personal/about/social_media/<int:pk>/delete/',
         views.DeleteSocialMediaView.as_view(), name='social_media-delete'),
    path('personal/about/description/add/',
         views.PublishUserDescriptionView.as_view(), name='add-user-description'),
    path('personal/about/description/update/', views.UpdateUserDescriptionView.as_view(),
         name='update-user-description'),
    path('personal/about/description/delete/', views.DeleteUserDescriptionView.as_view(),
         name='delete-user-description'),
    # Views for viewing reading history, clearing it completely and
    # deleting particular readings
    path('personal/reading_history/', views.ReadingHistory.as_view(),
         name='reading-history'),
    path('personal/reading_history/clear/', views.ClearReadingHistory.as_view(),
         name='clear-reading-history'),
    path('personal/reading_history/<int:pk>/delete/', views.DeleteUserReading.as_view(),
         name='delete-reading'),
    # views for viewing liked/disliked articles, clearing all likes/dislikes,
    # deleting particular likes/dislikes
    path('personal/articles/liked/',
         views.LikedArticlesView.as_view(), name='liked-articles'),
    path('personal/articles/disliked/',
         views.DislikedArticlesView.as_view(), name='disliked-articles'),
    path('personal/articles/liked/clear/',
         views.ClearLikesView.as_view(), name='clear-likes'),
    path('personal/articles/disliked/clear/',
         views.ClearDislikesView.as_view(), name='clear-dislikes'),
    path('personal/likes/<int:pk>/delete/',
         views.DeleteLikeView.as_view(), name='delete-like'),
    path('personal/dislikes/<int:pk>/delete/',
         views.DeleteDislikeView.as_view(), name='delete-dislike'),
    # View for seeing users that user is subscribed to
    path('personal/subscriptions/',
         views.SubscriptionsListView.as_view(), name='subscriptions-list'),
    # Views for seeing articles added to Favorites, clearing all favorites,
    # deleting particular articles from Favorites
    path('personal/articles/favorites/',
         views.FavoriteArticlesList.as_view(), name='favorite-articles'),
    path('personal/articles/favorites/<int:pk>/delete/', views.DeleteFavoriteArticle.as_view(),
         name='delete-favorite-article'),
    path('personal/articles/favorites/clear/', views.ClearFavoritesView.as_view(),
         name='clear-favorites')
]

core/models.py
from django.db import models
from django.core.exceptions import ValidationError
from taggit.managers import TaggableManager


def validate_image(image):

    file_size = image.file.size
    limit_mb = 5
    if file_size > limit_mb * 1024 * 1024:
        raise ValidationError(f"Maximum size of the image is {limit_mb} MB")


class Article(models.Model):
    title = models.CharField(max_length=255, null=False)
    content = models.TextField()
    author = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to='core/images', null=False, validators=[validate_image]
    )
    times_read = models.BigIntegerField(default=0)
    tags = TaggableManager(
        help_text='Use comma to separate tags, # is not needed to add tag')
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class SocialMedia(models.Model):
    FACEBOOK = 'FB'
    INSTAGRAM = 'IM'
    YOUTUBE = 'YB'
    TIKTOK = 'TT'
    TWITTER = 'TW'
    SOCIAL_MEDIA_TITLES = [
        (FACEBOOK, 'Facebook'),
        (INSTAGRAM, 'Instagram'),
        (YOUTUBE, 'Youtube'),
        (TIKTOK, 'TikTok'),
        (TWITTER, 'Twitter')
    ]
    user = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE)
    link = models.URLField(max_length=128, unique=True)
    title = models.CharField(max_length=2, choices=SOCIAL_MEDIA_TITLES)


class UserDescription(models.Model):
    user = models.OneToOneField('users.CustomUser', on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return self.content


class FavoriteArticles(models.Model):
    user = models.OneToOneField('users.CustomUser', on_delete=models.CASCADE)
    articles = models.ManyToManyField('core.Article')


class Reaction(models.Model):
    value = models.SmallIntegerField()
    user = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE)
    article = models.ForeignKey('core.Article', on_delete=models.CASCADE)
    reaction_date = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    user = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE)
    article = models.ForeignKey('core.Article', on_delete=models.CASCADE)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


class UserReading(models.Model):
    user = models.ForeignKey('users.CustomUser', on_delete=models.CASCADE)
    article = models.ForeignKey('core.Article', on_delete=models.CASCADE)
    date_read = models.DateTimeField()


class Subscription(models.Model):
    subscriber = models.ForeignKey(
        'users.CustomUser', related_name='subscriber', on_delete=models.CASCADE)
    subscribe_to = models.ForeignKey(
        'users.CustomUser', related_name='subscribe_to', on_delete=models.CASCADE)

personal/models.py
from django.db import models

# Create your models here.

personal/views.py
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models.query_utils import Q
from django.db.models import Sum
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView
from core.models import Subscription, Article, SocialMedia, UserDescription, FavoriteArticles, UserReading, Reaction
from personal.forms import PublishUpdateArticleForm, PublishSocialMediaForm, PublishUpdateUserDescriptionForm


class PersonalPageView(View):
    template_name = 'personal/personal_page.html'

    def get_subscribers(self, user):
        return Subscription.objects.\
            filter(subscribe_to=user).all().count()

    def get(self, request, *args, **kwargs):
        current_user = request.user
        subscribers = self.get_subscribers(current_user)
        return render(request, self.template_name, {'subscribers': subscribers})

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class SubscriptionsListView(ListView):
    model = Subscription
    template_name = 'personal/subscriptions_list.html'
    context_object_name = 'subscriptions'

    def get_queryset(self):
        current_user = self.request.user
        subscriptions = Subscription.objects.\
            select_related('subscribe_to').\
            filter(subscriber=current_user).all()
        return subscriptions

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ArticlesListView(ListView):
    model = Article
    template_name = 'personal/articles_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        current_user = self.request.user
        articles = Article.objects.\
            prefetch_related('tags').\
            filter(author=current_user).\
            order_by('-pub_date').all()
        return articles

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class ArticleDetailView(DetailView):
    queryset = Article.objects.select_related('author').all()
    template_name = 'personal/article_detail.html'
    context_object_name = 'article'

    def get(self, request, *args, **kwargs):
        article: Article = self.get_object()
        if article.author.id != request.user.id:
            raise PermissionDenied
        return super().get(request, *args, **kwargs)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class PublishArticleView(View):
    form_class = PublishUpdateArticleForm
    template_name = 'personal/publish_article.html'
    success_message = 'You successfully published new article'
    redirect_to = 'personal:articles-list'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            form.instance.author = request.user
            obj.save()
            form.save_m2m()
            messages.success(request, self.success_message)
            return redirect(self.redirect_to)
        return render(request, self.template_name, {'form': form})

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UpdateArticleBaseClass(View):
    form_class = PublishUpdateArticleForm
    template_name = 'personal/update_article.html'
    success_message = 'You successfully updated your article'
    redirect_to = ''
    article_pk_needed = False
    send_post_to = ''

    def get_article(self, pk):
        return Article.objects.\
            filter(pk=pk).\
            prefetch_related('tags').\
            first()

    def get(self, request, *args, **kwargs):
        article = self.get_article(self.kwargs['pk'])
        if not article:
            raise Http404
        if article.author != request.user:
            raise PermissionDenied
        form = self.form_class(instance=article)
        return render(request, self.template_name, {'form': form,
                                                    'article': article,
                                                    'send_post_to': self.send_post_to})

    def post(self, request, *args, **kwargs):
        article = self.get_article(self.kwargs['pk'])
        if not article:
            raise Http404
        if article.author != request.user:
            raise PermissionDenied
        form = self.form_class(request.POST, request.FILES, instance=article)
        if form.is_valid():
            obj = form.save(commit=False)
            # form.instance.author = request.user
            obj.save()
            form.save_m2m()
            messages.success(request, self.success_message)
            if self.article_pk_needed:
                return redirect(self.redirect_to, pk=article.id)
            else:
                return redirect(self.redirect_to)
        return render(request, self.template_name, {'form': form,
                                                    'article': article,
                                                    'send_post_to': self.send_post_to})

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class UpdateArticleThroughArticlesList(UpdateArticleBaseClass):
    """
    This view updates article and redirects to articles list
    """
    redirect_to = 'personal:articles-list'
    send_post_to = 'personal:update-article-list'


class UpdateArticleThroughArticleDetail(UpdateArticleBaseClass):
    """
    This view updates article and redirects to article detail.
    'article_pk_needed' is to know to detail of which article to redirect
    """
    article_pk_needed = True
    redirect_to = 'personal:article-detail'
    send_post_to = 'personal:update-article-detail'


class DeleteArticleView(View):
    success_message = 'You successfully deleted your article'
    redirect_to = 'personal:articles-list'

    def get_article(self, pk):
        return Article.objects.filter(pk=pk).first()

    def post(self, request, *args, **kwargs):
        current_user = request.user
        article = self.get_article(self.kwargs['pk'])
        if not article:
            raise Http404
        if article.author != current_user:
            raise PermissionDenied
        article.delete()
        messages.success(request, self.success_message)
        return redirect(self.redirect_to)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class AboutPageView(View):
    template_name = 'personal/about_page.html'
    form_class = PublishSocialMediaForm
    success_message = 'You successfully added new link to your social media'
    redirect_to = 'personal:about-page'

    def get_social_media(self, user):
        return SocialMedia.objects.\
            filter(user=user).\
            order_by('title').\
            all()

    def get_description(self, user):
        return UserDescription.objects.filter(user=user).first()

    def get_readings(self, user):
        return Article.objects.filter(author=user).aggregate(Sum('times_read'))

    def get(self, request, *args, **kwargs):
        current_user = request.user
        social_media_list = self.get_social_media(current_user)
        description = self.get_description(current_user)
        form = self.form_class()
        readings = self.get_readings(current_user)['times_read__sum']
        if not readings:
            readings = 0
        return render(request, self.template_name, {'form': form,
                                                    'social_media_list': social_media_list,
                                                    'description': description,
                                                    'readings': readings})

    def post(self, request, *args, **kwargs):
        current_user = request.user
        form = self.form_class(request.POST)
        if form.is_valid():
            form.instance.user = current_user
            form.save()
            messages.success(request, self.success_message)
            return redirect(self.redirect_to)
        social_media_list = self.get_social_media(current_user)
        description = self.get_description(current_user)
        readings = self.get_readings(current_user)['times_read__sum']
        return render(request, self.template_name, {'form': form,
                                                    'social_media_list': social_media_list,
                                                    'description': description,
                                                    'readings': readings})

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class DeleteSocialMediaView(View):
    success_message = 'You successfully deleted this social media link'
    redirect_to = 'personal:about-page'

    def get_social_media(self, pk):
        return SocialMedia.objects.filter(pk=pk).first()

    def post(self, request, *args, **kwargs):
        current_user = request.user
        social_media = self.get_social_media(self.kwargs['pk'])
        if not social_media:
            raise Http404
        if social_media.user != current_user:

personal/templates/personal/about_page.html
{% extends "core/header.html" %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container py-5">
    <div class="jumbotron">
        <h1>This is your "About page"</h1>
        <p> <strong>Date you joined Articlee:</strong> <mark>{{ user.date_joined.date }}</mark></p>
        <p><strong>Times your articles were read:</strong> <mark> {{ readings }}</mark></p>
    </div>
    <div class="container p-3 my-3 border">
        {% if not description %}
        <a href="{% url 'personal:add-user-description' %}">Add description about yourself</a>
        {% else %}
        <h3>Description: </h3>
        <a href="{% url 'personal:update-user-description' %}">Update description</a>
        <div class="container py-5">
            <p class="font-weight-bold text-break">
                {{ description }}
            </p>
        </div>
        <form action="{% url 'personal:delete-user-description' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete description</button>
        </form>
        {% endif %}
    </div>
    <div class="container p-3 my-3 border ">
        {% if social_media_list %}
        <h3>Social media links you added:</h3>
        {% for sm in social_media_list %}
        <form action="{% url 'personal:social_media-delete' sm.id %}" method="post" class="form-inline">
            <a href="{{ sm.link }}" class="mr-sm-2">{{ sm.get_title_display }}</a>
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm mr-sm-2">Delete link</button>
        </form> <br>
        {% endfor %}
        <form action="{% url 'personal:about-page' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Add link</button>
        </form>
        {% else %}
        <h2>Let users follow you on different social media: </h2>
        <form action="{% url 'personal:about-page' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Add link</button>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

personal/templates/personal/article_detail.html
{% extends "core/header.html" %}

{% block content %}
<div class="container py-5">
    <div class="jumbotron" style="height: 400px;">
        <h1>Article's title: {{ article.title }}</h1>
        <form action="{% url 'public:article-detail' article.id %}">
            <button class="btn btn-primary" type="submit">Read</button>
        </form>
        <img src="{{ article.image.url }}" alt="Article Image" class="img-thumbnail" style="width: 15%; float: right;">
        <p><strong>Published on:</strong> <mark>{{ article.pub_date.date }}</mark></p>
        <p><strong>Times read:</strong> <mark>{{ article.times_read }}</mark></p>
        <p><strong>Tags:</strong>
            {% for tag in article.tags.all %}
            <a href="{% url 'public:articles-tag' tag.slug %}">#{{ tag }}</a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <a href="{% url 'personal:update-article-detail' article.id %}">Update this article</a>
        <form action="{% url 'personal:delete-article' article.id%}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger">Delete article</button>
        </form>
    </div>
    <div class="container py-3 my-3 bg-primary text-white">
        <h3>Content:</h3>
        <p class="text-break">{{ article.content }}</p>
    </div>
</div>
{% endblock %}

personal/templates/personal/articles_list.html
{% extends "core/header.html" %}

{% block content %}
<div class="container py-5">
    <div class="container py-5">
        <h1>Number of articles you published: <mark>{{ articles|length }}</mark></h1>
        <h2><a href="{% url 'personal:publish-article' %}">Publish new article</a></h2>
    </div>
    <div class="card-columns">
        {% for article in articles %}
        <div class="card" style="width: 300px;">
            <a href="{% url 'personal:article-detail' article.id %}">
                <img class="card-img-top img-thumbnail" src="{{ article.image.url }}" alt="Article image">
            </a>
            <div class="card-body">
                <p class="text-info small">Click on thumbnail to see your personal page of the article</p>
                <h4>Title: {{ article.title }}</h4>
                <a href="{% url 'public:article-detail' article.id %}" class="btn btn-primary">Read</a> <br>
                <p class="card-text">
                    <strong>Tags:</strong>
                    {% for tag in article.tags.all %}
                    <a href="{% url 'public:articles-tag' tag.slug %}">#{{ tag }}</a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <p class="card-text"><strong>Published on:</strong> {{ article.pub_date.date }}</p>
                <p class="card-text"><strong>Times read:</strong> {{ article.times_read }}</p>
                <a href="{% url 'personal:update-article-list' article.id %}">Update article</a>
                <form method="post" action="{% url 'personal:delete-article' article.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete article</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

personal/templates/personal/disliked_articles.html
{% extends "core/header.html" %}

{% block content %}
<div class="container py-5">
    <h1>Number of articles you disliked: <mark>{{ reaction_objects|length }}</mark></h1>
    <form action="{% url 'personal:clear-dislikes' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Clear all your dislikes</button>
    </form>
    {% if reaction_objects %}
    <div class="container p-3 my-3 border">
        {% for ro in reaction_objects %}
        <form action="{% url 'personal:delete-dislike' ro.id %}" method="post" class="form-inline">
            <p class="mr-sm-2">
                -- You disliked article
                <a href="{% url 'public:article-detail' ro.article.id%}">{{ro.article.title}}</a>
                on <mark>{{ro.reaction_date.date }}</mark> |
            </p>
            {% csrf_token %}
            <button class="btn btn-danger btn-sm mb-2" type="submit">Delete dislike</button>
        </form> <br>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

personal/templates/personal/favorite_articles.html
{% extends "core/header.html" %}

{% block content %}
<div class="container py-5">
    <div class="container py-5">
        {% if not articles %}
        <h1>Number of your favorite articles: <mark>0</mark> </h1>
        {% else %}
        <h1>Number of your favorite articles: <mark>{{ articles|length }}</mark> </h1>
        {% endif %}
        <form action="{% url 'personal:clear-favorites' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Clear all your Favorites</button>
        </form>
    </div>
    <div class="card-columns">
        {% for article in articles %}
        <div class="card" style="width: 300px;">
            <img class="card-img-top img-thumbnail" src="{{ article.image.url }}" alt="Movie poster">
            <div class="card-body">
                <h4>Title: {{ article.title }}</h4>
                <a href="{% url 'public:article-detail' article.id %}" class="btn btn-primary">Read</a> <br>
                <p class="card-text">
                    <strong>Tags:</strong>
                    {% for tag in article.tags.all %}
                    <a href="{% url 'public:articles-tag' tag.slug %}">#{{ tag }}</a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <p class="card-text"><strong>Published on:</strong> {{ article.pub_date.date }}</p>
                <p class="card-text"><strong>Times read:</strong> {{ article.times_read }}</p>
                <form action="{% url 'personal:delete-favorite-article' article.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete from Favorites</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

personal/templates/personal/liked_articles.html
{% extends "core/header.html" %}

{% block content %}
<div class="container py-5">
    <h1>Number of articles you liked: <mark>{{ reaction_objects|length }}</mark></h1>
    <form action="{% url 'personal:clear-likes' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Clear all your likes</button>
    </form>
    {% if reaction_objects %}
    <div class="container p-3 my-3 border">
        {% for ro in reaction_objects %}
        <form action="{% url 'personal:delete-like' ro.id %}" method="post" class="form-inline">
            <p class="mr-sm-2">
                -- You liked article
                <a href="{% url 'public:article-detail' ro.article.id%}">{{ro.article.title}}</a>
                on <mark>{{ro.reaction_date.date }}</mark> |
            </p>
            {% csrf_token %}
            <button class="btn btn-danger btn-sm mb-2" type="submit">Delete like</button>
        </form> <br>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

personal/templates/personal/personal_page.html
{% extends "core/header.html" %}

{% block content %}
<div class="container py-5">
    <div class="jumbotron" style="height: 360px;">
        <h1>This is your personal page, {{ user }}</h1>
        {% if not user.user_image %}
        {% load static %}
        <img src="{% static 'users/profile_pic.jpg' %}" alt="User's profile image" style="width: 15%; float: right;"
            class="rounded-circle">
        {% else %}
        <img src="{{ user.user_image.url }}" alt="User's Profile Image" class="rounded-circle"
            style="width: 15%; float: right;">
        {% endif %}
        <div class="container py-5">
            <h2>Number of your subscribers: <mark> {{ subscribers }} </mark></h2>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="btn-group-vertical">
                    <a href="{% url 'personal:about-page' %}" class="btn btn-primary">Your about page</a>
                    <a href="{% url 'personal:articles-list' %}" class="btn btn-primary">Your articles</a>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="btn-group-vertical">
                    <a href="{% url 'personal:subscriptions-list' %}" class="btn btn-primary">Your subscriptions</a>
                    <a href="{% url 'personal:favorite-articles' %}" class="btn btn-primary">Your favorite articles</a>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="btn-group-vertical">
                    <a href="{% url 'personal:reading-history' %}" class="btn btn-primary">Your reading history</a>
                    <a href="{% url 'personal:liked-articles' %}" class="btn btn-primary">Articles you liked</a>
                    <a href="{% url 'personal:disliked-articles' %}" class="btn btn-primary">Articles you disliked</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

personal/templates/personal/publish_article.html
{% extends "core/header.html" %}

{% block content %}
{% load crispy_forms_tags %}
<div class="container py-5">
    <h1>Publish Your article</h1>
    <form action="{% url 'personal:publish-article' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Publish</button>
    </form>
</div>
{% endblock %}

personal/templates/personal/publish_description.html
{% extends "core/header.html" %}

{% block content %}
    {% load crispy_forms_tags %}
    <div class="container py-5">
        <h1>Leave your description to let users know more about you</h1>
        <form action="{% url 'personal:add-user-description' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Add description</button>
        </form>
    </div>
{% endblock %}

personal/templates/personal/reading_history.html
{% extends "core/header.html" %}

{% block content %}
<div class="container py-5">
    <h1>Your reading history</h1>
    <form action="{% url 'personal:clear-reading-history' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Clear your reading history</button>
    </form>
    {% if user_readings %}
    <div class="container p-3 my-3 border">
        {% for ur in user_readings %}
        <form action="{% url 'personal:delete-reading' ur.id %}" method="post" class="form-inline">
            <p class="mr-sm-2">
                -- You read article
                <a href="{% url 'public:article-detail' ur.article.id%}">{{ur.article.title}}</a>
                on <mark>{{ur.date_read.date }}</mark> |
            </p>
            {% csrf_token %}
            <button class="btn btn-danger btn-sm mb-2" type="submit">Delete from history</button>
        </form> <br>
        {% endfor %}
    </div>
    {% else %}
    <div class="container p-3 my-3 border">
        <h3>Your reading history is empty</h3>
    </div>
    {% endif %}
</div>
{% endblock %}

personal/templates/personal/update_description.html
{% extends "core/header.html" %}

{% block content %}
    {% load crispy_forms_tags %}
    <div class="container py-5">
        <h1>Leave your description to let users know more about you</h1>
        <form action="{% url 'personal:update-user-description' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Update your description</button>
        </form>
    </div>
{% endblock %}