articlee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('users.urls')),
    path('', include('personal.urls')),
    path('', include('public.urls')),
]


handler403 = 'core.views.error_403_handler'
handler404 = 'core.views.error_404_handler'

core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from core import views


app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('become_user/',
         TemplateView.as_view(template_name='core/become_user.html'), name='become-user'),
]

users/urls.py
from django.urls import path
from users.views import RegisterUserView, LoginUserView, logout_request, ChangeUserView


app_name = 'users'
urlpatterns = [
    path('register/', RegisterUserView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', logout_request, name='logout'),
    path('change-acc/', ChangeUserView.as_view(), name='change-user')
]

users/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser


def validate_image(image):

    file_size = image.file.size
    limit_mb = 5
    if file_size > limit_mb * 1024 * 1024:
        raise ValidationError(f"Maximum size of the image is {limit_mb} MB")


class CustomUser(AbstractUser):
    email = models.EmailField(
        unique=True, help_text='Required. Enter a valid email address.')
    user_image = models.ImageField(null=True, blank=True,
                                   upload_to='users/images', validators=[validate_image])

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm,\
    UserChangeForm as BaseUserChangeForm
from users.models import CustomUser


class UserCreationForm(BaseUserCreationForm):
    user_image = forms.ImageField(required=False, label='Profile image',
                                  help_text='You can register without an image.')

    class Meta:
        model = CustomUser
        fields = [
            'username', 'email', 'password1', 'password2', 'user_image'
        ]

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')

        if username and len(username) < 6:

            msg = 'Username cannot be shorter than 6 characters.'
            self.add_error('username', msg)

        return self.cleaned_data


class UserChangeForm(BaseUserChangeForm):
    password = None
    user_image = forms.ImageField(label='Profile image', required=False)

    class Meta:
        model = CustomUser
        fields = [
            'username', 'email', 'user_image'
        ]

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        if username and len(username) < 6:
            msg = 'Username cannot be shorter than 6 characters.'
            self.add_error('username', msg)

        return self.cleaned_data

users/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect
from django.views import View
from users.forms import UserCreationForm, UserChangeForm


class UserBaseView(View):
    # Base View for Register and Login to not to repeat "get" method
    # two times because it is the same
    form_class = None
    template_name = ''

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})


class RegisterUserView(UserBaseView):
    form_class = UserCreationForm
    template_name = 'users/register.html'

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'You were successfully registered')
            return redirect('core:index')
        return render(request, self.template_name, {'form': form})


class LoginUserView(UserBaseView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'

    def post(self, request):
        form = self.form_class(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                messages.success(
                    request, 'Welcome back')
                return redirect('core:index')
        return render(request, self.template_name, {'form': form})


def logout_request(request):
    logout(request)
    messages.success(request, 'You have successfully logged out.')
    return redirect('core:index')


class ChangeUserView(View):
    form_class = UserChangeForm
    template_name = 'users/change_user.html'

    def get(self, request):
        current_user = request.user
        form = self.form_class(instance=current_user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        current_user = request.user
        form = self.form_class(
            request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'You successfully changed your credentials')
            return redirect('core:index')
        return render(request, self.template_name, {'form': form})

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

users/templates/users/change_user.html
{% extends "core/header.html" %}

{% block content%}
    {% load crispy_forms_tags %}
    <div class="container py-5">
      <h1>Change your profile info</h1>
      <form action="{% url 'users:change-user' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Submit changes</button>
      </form>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends "core/header.html" %}

{% block content%}
    {% load crispy_forms_tags %}
    <div class="container py-5">
      <h1>Login</h1>
      <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %} 
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Login</button>
        <p class="text-center">
          Don't have an account?
          <a href="{% url 'users:register' %}">Create account</a>.
        </p>
      </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends "core/header.html" %}

{% block content%}
    {% load crispy_forms_tags %}
    <div class="container py-5">
      <h1>Register</h1>
      <form action="{% url 'users:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Register</button>
        <p class="text-center">
          If you already have an account
          <a href="{% url 'users:login' %}">Login</a>.
        </p>
      </form>
    </div>
{% endblock %}